version: "3"
services:
  db:
    image: postgres:latest
    user: postgres
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "rooter"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
      - ./database/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./database/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "50001:5432"
    networks:
      - unip_net

  parser:
    build: parser/
    restart: always
    depends_on:
      - db
    networks:
      - unip_net

  backend:
    build: backend
    restart: always
    depends_on:
      - db
    ports:
      - "50000:80"
    networks:
      - unip_net

  frontend:
    build: frontend
    restart: always
    environment:
      BOT_TOKEN: "6949424987:AAHMCBHGNEP0O-Dr9z-vTDSNsSiTZ7Yl5gk"
    depends_on:
      - db
    networks:
      - unip_net

volumes:
  postgres-data:
    driver: local

networks:
  unip_net:
